# docker-compose.prod.yml
services:
  gold_front:
    container_name: gold_front
    image: gold_front
    restart: always
    networks:
      - interservices

networks:
  interservices:
    external: true